name: una_social
description: "Una Social"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+344
# A Flutter project to create a social app using Supabase and GoRouter  

environment:
  sdk: '>=3.4.0 <4.0.0' # Aggiorna se necessario, compatibile con Dart 3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter       

  # Dipendenze verso i tuoi pacchetti locali
  una_chat:
    path: packages/una_chat

  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  file_saver: ^0.3.0
  flutter_dotenv: ^5.1.0 # Per gestire le credenziali
  get: ^4.7.2
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  logging: ^1.3.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.9.1 
  supabase: ^2.8.0
  syncfusion_flutter_core: ^30.1.38
  syncfusion_flutter_datagrid: ^30.1.38
  universal_html: ^2.2.4
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Aggiungi questa riga per includere il file .env
  assets:
    - .env
