name: una_chat # Nome univoco del pacchetto. Cruciale!
description: La versione pubblica di Whatsapp.
version: 0.0.1 # O 1.0.0+1, ecc.
publish_to: 'none' 

environment:
  sdk: '>=3.4.0 <4.0.0' # Aggiorna se necessario, compatibile con Dart 3.6.1


dependencies:
  flutter:
    sdk: flutter # Essenziale per quasi tutti i pacchetti UI Flutter
  una_social:
    path: ../../  # Questo percorso va da 'packages/una_chat/' alla root
      
  country_picker: ^2.0.27


dev_dependencies:
  flutter_test:
    sdk: flutter # Per scrivere test per i widget di una_chat
  flutter_lints: ^2.0.0 # O un altro pacchetto di linting

# Sezione specifica di Flutter (se il pacchetto ha asset, font, plugin nativi, ecc.)
flutter:
  uses-material-design: true

  # Se una_chat ha i suoi asset (immagini, suoni di notifica specifici per la chat, ecc.)
  # Gli path sono relativi alla root del pacchetto una_chat
  # assets:
  #   - assets/images/chat_background.png
  #   - assets/sounds/new_message_tone.mp3

  # Se una_chat definisce o usa font specifici non globali per l'app
  # fonts:
  #   - family: ChatFont
  #     fonts:
  #       - asset: fonts/ChatFont-Regular.ttf
  #       - asset: fonts/ChatFont-Bold.ttf
  #         weight: 700